name: sample_dart_cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  args: ^2.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
