name: my_conditional_lib
description: A sample lib using conditional import.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
